version: 2.1
orbs:
  scan: prisma_cloud/devops_security@2.0.0
jobs:
  scan_iac: scan/prisma_cloud
  
workflows:
  scan:
    jobs:
      - scan_iac:
          prisma_cloud_api_url: https://api-sl.qa.prismacloud.io
          access_key: 82b530a7-b6fb-4613-aa95-7e42bd41bc6a
          secret_key: PC_SECRET_KEY
          failure_criteria_high_severity: 1
          failure_criteria_medium_severity: 1
          failure_criteria_low_severity: 1
          failure_criteria_operator: or
